services:
  medioteca-backend:
    image: medioteca-backend
    build:
      context: ./BackEnd
    container_name: medioteca-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Local=Data Source=/app/data/Medioteca.db
    volumes:
      - ./Data:/app/data

  medioteca-frontend:
    image: medioteca-frontend
    build:
      context: ./FrontEnd
    container_name: medioteca-frontend
    ports:
      - "3000:3000"
    depends_on:
      - medioteca-backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - medioteca-frontend
      - medioteca-backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the NGINX config file
